/* generated by scripts/fetch-avatars.js — frontpage "connections" row.
   the order is shuffled on every page load, so everyone shows up over time. */
window.__UMBRA_CONNECTIONS = [
  {"username":"noshergfx","name":"nosher","verified":false,"src":"assets/frontpage/avatars/noshergfx.png"},
  {"username":"Ieafarr","name":"rafaeI","verified":false,"src":"assets/frontpage/avatars/ieafarr.png"},
  {"username":"4Iudee","name":"lude","verified":false,"src":"assets/frontpage/avatars/4iudee.png"},
  {"username":"JuanArtxz","name":"juan","verified":false,"src":"assets/frontpage/avatars/juanartxz.png"},
  {"username":"sak7q","name":"sak","verified":false,"src":"assets/frontpage/avatars/sak7q.png"},
  {"username":"zLyuss","name":"Lyus","verified":false,"src":"assets/frontpage/avatars/zlyuss.png"},
  {"username":"ThzArtzz","name":"THZ","verified":false,"src":"assets/frontpage/avatars/thzartzz.png"},
  {"username":"guto65","name":"guto65","verified":false,"src":"assets/frontpage/avatars/guto65.png"},
  {"username":"killiozz","name":"killiozz","verified":true,"src":"assets/frontpage/avatars/killiozz.png"},
  {"username":"EngineerNamedEric","name":"Eric","verified":false,"src":"assets/frontpage/avatars/engineernamederic.png"},
  {"username":"ClassicDivines","name":"ClassicDivines","verified":false,"src":"assets/frontpage/avatars/classicdivines.png"},
  {"username":"Monkeyrdh","name":"Monkeyrdh","verified":false,"src":"assets/frontpage/avatars/monkeyrdh.png"},
  {"username":"ToshiArtz","name":"Toshi","verified":false,"src":"assets/frontpage/avatars/toshiartz.png"},
  {"username":"7SuecoXz","name":"7Sueco","verified":false,"src":"assets/frontpage/avatars/7suecoxz.png"},
  {"username":"ghkmuitomassa","name":"ghkmuitomassa","verified":true,"src":"assets/frontpage/avatars/ghkmuitomassa.png"},
  {"username":"Art_Pkrl0","name":"art","verified":false,"src":"assets/frontpage/avatars/art_pkrl0.png"},
  {"username":"ssquibidyy","name":"squibidy","verified":false,"src":"assets/frontpage/avatars/ssquibidyy.png"}
];
