#!/usr/bin/env node
/* Frontpage "connections" row: resolves roblox usernames, downloads their avatar headshots into
   assets/frontpage/avatars/ and writes js/connections.js.
   Headshot CDN urls expire (30DAY-…), so the images are saved into the repo instead of hotlinked.
   Usage: node scripts/fetch-avatars.js   (Node 18+, zero deps) */
'use strict';
const fs = require('fs');
const path = require('path');

const USERNAMES = [
  'noshergfx', 'Ieafarr', '4Iudee', 'JuanArtxz', 'sak7q', 'zLyuss', 'ThzArtzz', 'guto65',
  'killiozz', 'EngineerNamedEric', 'ClassicDivines', 'Monkeyrdh', 'ToshiArtz', '7suecoxz', 'ghkmuitomassa', 'Art_Pkrl0',
];

const ROOT = path.join(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'assets', 'frontpage', 'avatars');
const OUT_JS = path.join(ROOT, 'js', 'connections.js');
const SIZE = '180x180';

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function fetchJson(url, opts, tries = 5) {
  for (let i = 0; i < tries; i++) {
    const res = await fetch(url, opts);
    if (res.ok) return res.json();
    if (res.status === 429 || res.status >= 500) { await sleep(1000 * (i + 1)); continue; }
    throw new Error(`${res.status} ${url}`);
  }
  throw new Error(`gave up after ${tries} tries: ${url}`);
}

async function main() {
  const users = await fetchJson('https://users.roblox.com/v1/usernames/users', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ usernames: USERNAMES, excludeBannedUsers: true }),
  });
  const byName = new Map(users.data.map((u) => [u.requestedUsername.toLowerCase(), u]));
  const found = USERNAMES.map((n) => byName.get(n.toLowerCase())).filter(Boolean);
  const missing = USERNAMES.filter((n) => !byName.has(n.toLowerCase()));

  // headshots can come back "Pending" while roblox renders them — poll until Completed
  const thumbs = new Map();
  const ids = found.map((u) => u.id).join(',');
  for (let attempt = 0; attempt < 6 && thumbs.size < found.length; attempt++) {
    if (attempt) await sleep(1500);
    const t = await fetchJson(`https://thumbnails.roblox.com/v1/users/avatar-headshot?userIds=${ids}&size=${SIZE}&format=Png&isCircular=false`);
    t.data.forEach((d) => { if (d.state === 'Completed' && d.imageUrl) thumbs.set(d.targetId, d.imageUrl); });
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });
  const entries = [];
  for (const u of found) {
    const url = thumbs.get(u.id);
    if (!url) { console.warn(`no headshot yet for ${u.name}`); continue; }
    const res = await fetch(url);
    if (!res.ok) { console.warn(`download failed for ${u.name} (${res.status})`); continue; }
    const file = `${u.name.toLowerCase()}.png`;
    fs.writeFileSync(path.join(OUT_DIR, file), Buffer.from(await res.arrayBuffer()));
    entries.push({ username: u.name, name: u.displayName || u.name, verified: !!u.hasVerifiedBadge, src: `assets/frontpage/avatars/${file}` });
  }

  // a pending headshot or failed download is transient: keep yesterday's list rather than
  // dropping someone for a day. (not found / banned is a real change and still goes through.)
  if (!entries.length || entries.length < found.length) {
    console.error(`only ${entries.length}/${found.length} avatars fetched — keeping the existing js/connections.js`);
    process.exit(1);
  }
  // complete run: drop avatar files for people no longer in the list
  {
    const keep = new Set(entries.map((e) => path.basename(e.src)));
    for (const f of fs.readdirSync(OUT_DIR)) {
      if (f.endsWith('.png') && !keep.has(f)) { fs.unlinkSync(path.join(OUT_DIR, f)); console.log(`removed stale ${f}`); }
    }
  }
  const js = '/* generated by scripts/fetch-avatars.js — frontpage "connections" row.\n'
    + '   the order is shuffled on every page load, so everyone shows up over time. */\n'
    + 'window.__UMBRA_CONNECTIONS = [\n'
    + entries.map((e) => '  ' + JSON.stringify(e)).join(',\n')
    + '\n];\n';
  fs.writeFileSync(OUT_JS, js);
  console.log(`wrote ${entries.length}/${USERNAMES.length} avatars`);
  if (missing.length) console.log(`not found or banned: ${missing.join(', ')}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
